global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: node-bench
    static_configs:
      - targets: ["10.10.10.104:9100"]
        labels: {hostname: jmqtt-broker}
      - targets: ["10.10.10.105:9100"]
        labels: {hostname: bench-device}
      - targets: ["10.10.10.106:9100"]
        labels: {hostname: bench-device-2}
      - targets: ["10.10.10.128:9100"]
        labels: {hostname: bench-kafka}
      - targets: ["10.10.10.129:9100"]
        labels: {hostname: bench-monitor}
      - targets: ["10.10.10.130:9100"]
        labels: {hostname: bench-backend}
      - targets: ["10.10.10.131:9100"]
        labels: {hostname: bench-redis}
      - targets: ["10.10.10.170:9100"]
        labels: {hostname: jmqtt-broker-a}
      - targets: ["10.10.10.171:9100"]
        labels: {hostname: jmqtt-broker-b}
      - targets: ["10.10.10.44:9100"]
        labels: {hostname: pve}
    relabel_configs:
      - source_labels: [hostname]
        target_label: instance
  - job_name: jmqtt-broker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["10.10.10.104:8922"]
        labels: {hostname: jmqtt-broker}
      - targets: ["10.10.10.170:8922"]
        labels: {hostname: jmqtt-broker-a}
      - targets: ["10.10.10.171:8922"]
        labels: {hostname: jmqtt-broker-b}
    relabel_configs:
      - source_labels: [hostname]
        target_label: instance
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
